// output/svelte/src/input.svelte
<script>
  const arabicToEnglish = (string) =>
    string.replace(/[٠-٩]/g, (digit) => "٠١٢٣٤٥٦٧٨٩".indexOf(digit));

  let name = "";
</script>

<label>This input changes arabic numbers to english numbers! </label>

<input
  value={name}
  on:input={(event) => {
    name = arabicToEnglish(event.target.value);
  }}
/>

// output/vue/vue3/src/input.vue
<template>
  <label>This input changes arabic numbers to english numbers! </label>

  <input
    :value="number"
    @input="number = arabicToEnglish($event.target.value)"
  />
</template>

<script>
const arabicToEnglish = (string) =>
  string.replace(/[٠-٩]/g, (digit) => "٠١٢٣٤٥٦٧٨٩".indexOf(digit));

export default {
  name: "my-component",

  data: () => ({ number: "" }),

  methods: { arabicToEnglish },
};
</script>
